version: '3'

services:
  api:
    container_name: sqlite_flask_api
    build:
      context: ./
      dockerfile: Dockerfile
    command: python main.py
    working_dir: /app
    ports:
      - "8080:8080"
    volumes:
      - ./:/app
